### ISSUE TITLE
Node.js 12 actions are deprecated

### ISSUE THREAD

**Issue by hectoralos** [apertium/github-actions#2]
https://github.com/apertium/apertium-fra/actions/runs/3772023945

> [call-workflow / build](https://github.com/apertium/apertium-fra/actions/runs/3772023945/jobs/6413857751)
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

**Comment by hectoralos** [comment]
There is no rush at all, but now I get:

> [Invalid workflow file: .github/workflows/monolingual.yml#L11](https://github.com/apertium/apertium-fra/actions/runs/3767288177/workflow)
> error parsing called workflow "apertium/github-actions/.github/workflows/monolingual-build.yml@master": failed to fetch workflow: reference to workflow should be either a valid branch, tag, or commit

https://github.com/apertium/apertium-fra/actions/runs/3767288177

**Comment by TinoDidriksen** [comment]
I have renamed the branch back to `master`. It is abysmal that git that can't bind to `HEAD`
